name: Code Quality (Lint)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM and Clang Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy cmake libboost-all-dev

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libpq-dev libpqxx-dev nlohmann-json3-dev

      - name: Generate Compilation Database
        run: |
          cmake -S . -B build-root -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake -S frontend -B build-frontend -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang-Format Check
        run: |
          find . -not -path '*/build/*' \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -print0 \
          | xargs -0 -r clang-format --style=file --dry-run -Werror
